config/routes.rb
Rails.application.routes.draw do
  # There is only one controller with only three methods,
  # so we limit the access to only the active ones
  resources :anagrams, only: [:index, :create, :show]
  root to: 'anagrams#index'
end

app/models/anagram.rb
# Anagram class
# It is a basic model, not an active model for choice.
# To improve the speed, I decided to store all the words list in RAM, without the use of an external database
# In fact, the bigger words database that I found on the web, is almost 3.5 MB, so can be loaded on RAM on the
# most part of new PC.
class Anagram
  # Constant used only in method 3
  CHAR_MAP ={ "a" => 2, "b" => 3, "c" => 5, "d" => 7, "e" => 11, "f" => 13, "g" =>17, "h" =>19, "i" => 23, "j" => 29, "k" => 31, "l" => 37, "m" => 41, "n" =>43, "o" =>47, "p" => 53, "q" =>59, "r" => 61, "s" => 67, "t" => 71, "u" => 73, "v" => 79, "w" => 83, "x" => 89, "y" => 97, "z" => 101, "'" => 103 }

  # We define some class attributes: we use attr_accessor instead of a manual definition because in recent version
  # the speed is almost identical
  # * file: is the uploaded file
  # * time_file: is the time for reading and processing the file
  # * word_hash: is the hash where we store the anagrams (after the upload)
  # * messages: is the lines of message inside the text area
  attr_accessor :file_name, :time_file, :words_hash

  # We initialize word_hash as an Hash and messages as a string
  def initialize
    self.file_name = nil
    self.words_hash = {}
  end

  # Function to populate the hash with all the anagrams.
  # * words is a string of words separated by newline (\n)
  def populate(words)
    # Create an array of words and normailze it: we delete all cr chars (\r) and put all letters downcase
    words = words.downcase.delete("\r").split("\n")
    # The anagram words contain the same letters, so we can create an hash where the key is a common index,
    # and the value is an array of words with the same key
    self.words_hash = words.each_with_object(Hash.new []) do |word,hash|
      hash[create_index(word)] += [word]
    end
  end

  # Function to create the hash index
  # we use one of the privates function below to create an index for every group of anagram
  # I tried more than one, just to find the better option
  def create_index(word)
    create_index1(word)
  end

  private

  # Method 1: we use internal chars function added in ruby 1.9.3 to split the word in an array of letters, sort the letters
  # with sort! and re-join the letters with join to have the ordered word
  def create_index1(word)
    word.chars.sort!.join
  end

  # Method 2: we convert every char of the word in a prime number in order to create a numeric signature
  def create_index2(word)
    word.each_char.map {|c| CHAR_MAP[c.downcase]}.reduce(:*)
  end

  # Method 3; like te first, but we use original 1.8 split function instead of chars
  def create_index3(word)
    word.split('').sort!.join
  end
end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  require 'benchmark'

  # The index page: to improve the readability, we check the dimension of the measured time
  # and convert it in milliseconds if is < 1
  def index
    unless $anagram.time_file.nil?
      if $anagram.time_file.real < 1
        @time = ($anagram.time_file.real*1000).round(3).to_s + ' ms'
      else
        @time = ($anagram.time_file.real).round(2).to_s + ' sec'
      end
    end

    @messages = session[:tmp_messages]
    session[:tmp_message] = nil
  end

  # Here we handle the upload and process of the file
  def create
    # if the user press the upload button without choosing the file
    if params[:anagram].nil? or params[:anagram][:file].nil?
      flash.now[:error] = 'Please, choose a file'
      render :index
    else
      $anagram.time_file = Benchmark.measure do
        # We populate the hash reading the file in RAM
        $anagram.populate(params[:anagram][:file].read)
        # Last we reset the $anagram.file_name global variable only with the filename to free some RAM
        $anagram.file_name = params[:anagram][:file].original_filename
        # Free
      end
      redirect_to root_url
    end
  end

  # Word search
  def show
    # First we downcase the word and initialize the anagrams array
    if params[:anagram].nil?
      word = params[:id].downcase
      old_messages = ''
    else
      word = params[:anagram][:word].downcase
      old_messages = params[:anagram][:messages]
    end

    anagrams =[]
    # Get the array of words from the hash
    total = Benchmark.measure do
      anagrams = $anagram.words_hash[$anagram.create_index(word)]
    end
    # Respond to html with a redirect and json
    respond_to do |format|
      format.html do
        # Add the message for the text area and store it in a temporary session
        session[:tmp_messages] = add_message(anagrams,word,total,old_messages)
        redirect_to root_url
      end
      format.json do
        render json: {word: word, anagrams: anagrams, total: total}
      end
    end
  end

  private

  # Function to add the message to the text area
  # I prefer to add the last message on top and not at the end
  # because it's easy to read it
  def add_message(anagrams,word,total,messages)
    # First: date and time for the search
    new_messages = "#{Time.now}\n"
    if anagrams.nil? or anagrams.count == 0
      # No anagram found
      new_messages += "0 anagrams found for #{word}\n\n"
    else
      # we have one or more anagrams
      new_messages +="#{anagrams.count} anagrams found for '#{word}' in #{(total.real*1000).round(3)} ms\n"
      new_messages += "> #{anagrams.join(', ')}\n\n"
    end
    # Add the message at the top
    new_messages + messages.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/anagrams_helper.rb
module AnagramsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anagrams/_search.html.erb
<div class="row">
  <div class="twelve columns">
    <p>Enter a word to search for anagram</p>
  </div>
</div>


<%= form_for :anagram, url: anagram_path(:anagram), method: :get  do |f| %>
  <div class="row">
    <div class="eight columns">
      <%=f.text_field :word %>
    </div>
    <div class="four columns">
      <%=f.submit 'Go' %>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%=f.text_area :messages, value: @messages, class: 'u-full-width', readonly: true %>
    </div>
  </div>
<% end %>

app/views/anagrams/_upload.html.erb
<%= form_for :anagram, url: anagrams_path(:anagram), method: :post  do |f| %>
  <div class="row">
    <div class="eight columns">
      <%=f.file_field :file %>
    </div>
    <div class="four columns">
      <%=f.submit 'load new dictionary' %>
    </div>
  </div>

<% end %>

<% unless $anagram.file_name.nil? %>
  <div class="row">
    <div class="twelve columns">
      <%=$anagram.file_name%> loaded in <%=@time%>
    </div>
  </div>
<% end %>

app/views/anagrams/index.html.erb
<div class="container">
  <div class="row">
    <div class="twelve columns">
      <h1>Anagram Finder</h1>
    </div>
  </div>

  <%= render 'layouts/flashes' %>

  <hr>

  <%= render 'anagrams/upload' %>

  <hr>

  <%= render 'anagrams/search' %>

</div>

app/views/layouts/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="row">
    <div class="twelve columns">
      <%= content_tag :div, msg, class: name %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnagramFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>